[tool.pdm]

[project]
name = ""
version = ""
description = ""
authors = [
    {name = "", email = ""},
]
dependencies = [
    "fastapi>=0.95.1",
    "uvicorn>=0.21.1",
]
requires-python = ">=3.10"
license = {text = "MIT"}
